version: "3.9"

services:
  backend-user:
    container_name: cicd-backend-user
    build:
      context: ./cicd-backend-user
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8091:8091"
    networks:
      - cicd-net

  backend-news:
    container_name: cicd-backend-news
    build:
      context: ./cicd-backend-news
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8092:8092"
    networks:
      - cicd-net

  frontend-manage:
    container_name: cicd-frontend-manage
    build:
      context: ./cicd-frontend-manage
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend-user
      - backend-news
    ports:
      - "80:80"
    networks:
      - cicd-net

networks:
  cicd-net:
    driver: bridge
