apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-backend-news
spec:
  selector:
    matchLabels:
      app: cicd-backend-news
  replicas: 1
  template:
    metadata:
      labels:
       app: cicd-backend-news 
    spec:
      imagePullSecrets:
      - name: private-registry   
      containers:
      - name: cicd-backend-news
        imagePullPolicy: Always
        image: localhost:8082/cicd-backend-news:20221216222725
        ports:
        - containerPort: 8092
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: host
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: port   
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: database  
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-auth
              key: username  
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-auth
              key: password                  