

kubectl create secret docker-registry private-registry \
--docker-username=cow3530 \
--docker-password=qwqwqw78 \
--docker-email=admin@example.org  \
--docker-server=localhost:8082 \


kubectl create secret generic mysql-auth --from-literal=username=root --from-literal=password=qwqwqw78 